version: '3.4'

networks:
  monitoring-system:
    external: true
    name: "${PROJECT}"

services:

  rabbitmq:
    image: rabbitmq:3.9.29
    container_name: rabbitmq
    user: "${UID}:${GID}"
    restart: on-failure
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - "${PROJECT}"

  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ${HOST_PWD}/monitoring_system/db/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - "${PROJECT}"

  redis:
    image: redis:6.0
    container_name: redis
    restart: on-failure
    volumes:
      - /var/log/redis:/var/log/redis
    healthcheck:
      test: redis-cli ping = "PONG"
      interval: 10s
      timeout: 5s
      retries: 5
    command: --save 30 1
    networks:
      - "${PROJECT}"

  file-generator-worker:
    image: monitoring-system
    build:
      target: monitoring-system
    depends_on:
      - rabbitmq
      - redis
    container_name: file-generator-worker
    volumes:
      - /tmp:/tmp
    environment:
      METHOD: file-generator-worker
      CELERY_DIR: "${CELERY_DIR}"
    restart: on-failure
    networks:
      - "${PROJECT}"

  redis-setter-worker:
    image: monitoring-system
    build:
      target: monitoring-system
    depends_on:
      - rabbitmq
      - redis
    container_name: redis-setter-worker
    environment:
      METHOD: redis-setter
    restart: on-failure
    networks:
      - "${PROJECT}"

  backup-tasks-to-db:
    image: monitoring-system
    build:
      target: monitoring-system
    depends_on:
      - rabbitmq
      - redis
      - postgres
    container_name: backup-tasks-to-db-worker
    environment:
      METHOD: backup-tasks-to-db
    restart: on-failure
    networks:
      - "${PROJECT}"

  celery-beat:
    image: monitoring-system
    build:
      target: monitoring-system
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - file-generator-worker
      - backup-tasks-to-db
      - redis-setter-worker
    container_name: celery-beat
    environment:
      METHOD: beat
    restart: on-failure
    networks:
      - "${PROJECT}"

  flower:
    image: mher/flower:1.2
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "5555:5555"
    container_name: flower
    environment:
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
    restart: on-failure
    networks:
      - "${PROJECT}"

  grafana:
    image: grafana/grafana:main-ubuntu
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ${HOST_PWD}/monitoring_system/grafana/dashboards:/var/lib/grafana/dashboards
      - ${HOST_PWD}/monitoring_system/grafana/provisioning/dashboards/all.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ${HOST_PWD}/monitoring_system/grafana/provisioning/datasources/all.yml:/etc/grafana/provisioning/datasources/all.yml
    container_name: grafana
    restart: on-failure
    networks:
      - "${PROJECT}"

  prometheus:
    image: prom/prometheus:main
    depends_on:
      - flower
    ports:
      - "9090:9090"
    volumes:
      - ${HOST_PWD}/monitoring_system/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    entrypoint:
      - "/bin/prometheus"
      - "--config.file=/etc/prometheus/prometheus.yml"
    container_name: prometheus
    restart: on-failure
    networks:
      - "${PROJECT}"

  telegraf:
    image: telegraf:1.29.3
    container_name: telegraf
    restart: on-failure
    depends_on:
      - influxdb
    volumes:
      - ${HOST_PWD}/monitoring_system/telegraf:/etc/telegraf/telegraf.d:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8125:8125"
      - "8092:8092"
      - "8094:8094"
    labels:
      - "docker.group=${PROJECT}"
    environment:
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
      DOCKER_INFLUXDB_INIT_ORG: "${DOCKER_INFLUXDB_INIT_ORG}"
      DOCKER_INFLUXDB_INIT_BUCKET: "${DOCKER_INFLUXDB_INIT_BUCKET}"
    networks:
      - "${PROJECT}"

  influxdb:
    image: influxdb:2.7.5-alpine
    container_name: influxdb
    restart: on-failure
    volumes:
      - /tmp/monitoring_system/influxdb:/var/lib/influxdb2
    ports:
      - "8086:8086"
    labels:
      - "docker.group=${PROJECT}"
    environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: "${DOCKER_INFLUXDB_INIT_USERNAME}"
        DOCKER_INFLUXDB_INIT_PASSWORD: "${DOCKER_INFLUXDB_INIT_PASSWORD}"
        DOCKER_INFLUXDB_INIT_ORG: "${DOCKER_INFLUXDB_INIT_ORG}"
        DOCKER_INFLUXDB_INIT_BUCKET: "${DOCKER_INFLUXDB_INIT_BUCKET}"
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
    networks:
      - "${PROJECT}"
