# provisioning/datasources/all.yml
apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    url: postgres:5432
    database: monitoring_system
    user: guest
    access: proxy
    isDefault: true
    editable: true
    secureJsonData:
      password: 'guest'
    jsonData:
      sslmode: "disable"
      postgresVersion: 15.2
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
