{
 "title": "Postgres Monitoring",
 "tags": [
  "monitoring",
  "number-of-rows"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dec",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM images ORDER BY id DESC;"
    }
   ]
  },
  {
   "title": "Number of rows",
   "type": "gauge",
   "description": "Number of records in table images",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT count(*) FROM images;" }
   ]
  },
  {
   "title": "Insert Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
   "targets": [
    { "rawSql": "SELECT * FROM images;" }
   ]
  }
 ]
}